pipeline {

  agent {
    docker {
      image 'python:2.7.16-slim'

    }
  }

    stages {
        stage('build') {
            when {
              changeset '**/vote/**'
            }
            steps {
                echo 'Building vote app'
                dir('vote') {
                  sh 'pip install -i requirements.txt'
                }
            }
        }
        stage('test') {
            when {
              changeset '**/vote/**'
            }
            steps {
                echo 'Running unit test on vote app'
                dir('vote') {
                  sh 'nosetests -v'
                }
            }
        }
    }
    post{
        always{
	    slackSend (channel: "lfs261", message: "vote-app: Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
            echo 'Pipeline for vote app has finished!!!'
        }
	failure{
	    slackSend (channel: "lfs261", message: "vote-app: Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
	}
	success{
	    slackSend (channel: "lfs261", message: "vote-app: Build Success - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
	}
    }
}
