version: "3.3"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
    networks:
      - instavote

  vote:
    image: linuxpizzacats/vote:master
    build: ./vote
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote

  result:
    image: linuxpizzacats/result:master
    build: ./result
    ports:
      - 5001:4000
      - 5002:80
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: linuxpizzacats/worker:master
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - instavote
