pipeline {
    agent any

    tools {
      maven 'Maven 3.6.1'
    }

    stages {
        stage('build') {
            steps {
                echo 'Compiler worker'
                dir('worker') {
                  sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Running unit test on worker app'
                dir('worker') {
                  sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            steps {
                echo 'Package worker app'
                dir('worker') {
                  sh 'mvn package'
                }
            }
        }
    }
    post{
        always{
            echo 'Pipeline for worker app has finished.'
        }
    }
}
